In [9]:
def add_number(x,y):
    return(x+y)

a=add_number
a(1,2)

3

In [2]:
def add_number(x,y,z=None):
    if(z==None):
        return(x+y)
    else:
        return(x+y+z)
    
print(add_number(1,2))
print(add_number(1,2,3))

3
6


In [8]:
def add_number(x,y,z=None,flag=True):
    if(flag):
        print("flag is true")
        
    if(z==None):
        return(x+y)
    else:
        return(x+y+z)
print(add_number(1,2,flag=True))
print(add_number(1,2,5,flag=False))
print(add_number(1,2,flag=True))

flag is true
3
8
flag is true
3


In [10]:
type(add_number)

function

In [12]:
type('this is a string')


str

In [15]:
type(1)

SyntaxError: invalid syntax (<ipython-input-15-60e376144998>, line 1)

In [17]:
x=(1,'a',2,3)
type(x)


tuple

In [18]:
x=[1,'b',2,3]

In [19]:
x

[1, 'b', 2, 3]

In [20]:
type(x)

list

In [21]:

x.append(3.25)
x

[1, 'b', 2, 3, 3.25]

In [22]:
type(x)

list

In [25]:
x=[1, 'b', 2, 3, 3.25]

In [26]:
x

[1, 'b', 2, 3, 3.25]

In [27]:
for item in x:
    print(item)

1
b
2
3
3.25


In [28]:
i=0
while(i!=len(x)):
    print(x[i])
    i=i+1

1
b
2
3
3.25


In [29]:
(1,2)+(3,4)

(1, 2, 3, 4)

In [30]:
[1,2]+[3,4]

[1, 2, 3, 4]

In [32]:
[1]*3

[1, 1, 1]

In [33]:
1 in [1,2,3]

True

In [34]:
x= 'This is a string'
print(x[0])
print(x[0:1])
print(x[0:2])

T
T
Th


In [35]:
x[-1]

'g'

In [36]:
x[-4:-2]

'ri'

In [37]:
x[:3]

'Thi'

In [38]:
x[3:]

's is a string'

In [45]:
firstname = 'Christopher'
lastname = 'Brooks'
print(firstname +' ' + lastname)
print(firstname*3)
print('Chris' in firstname)

Christopher Brooks
ChristopherChristopherChristopher
True


In [47]:
firstname = 'Christopher arthur hansen brooks'.split(' ')[0]
lastname = 'Christopher arthur hansen brooks'.split(' ')[-1]
print(firstname)
print(lastname)

Christopher
brooks


In [48]:
'Chris' + 2

TypeError: can only concatenate str (not "int") to str

In [49]:
'Chris' + str(2)

'Chris2'

In [50]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks']

'brooksch@umich.edu'

In [1]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson'] 

NameError: name 'x' is not defined

In [53]:
for name in x:
    print(x[name])

brooksch@umich.edu
billg@microsoft.com
None


In [54]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
None


In [55]:
for name , email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


In [56]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [57]:
fname

'Christopher'

In [58]:
lname

'Brooks'

In [59]:
email

'brooksch@umich.edu'

In [60]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email = x

ValueError: too many values to unpack (expected 3)

In [63]:
print('Chris' + str(2))

Chris2


In [66]:
sales_record = {
    'price' : 3.24,
    'num_items' : 4,
    'person' : 'Chris'
}
sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'
print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


In [72]:
import csv

%precision 4

with open ('/root/Downloads/mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
mpg[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [73]:
len(mpg)

234

In [76]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [77]:
sum(float(d['cty']) for d in mpg)/len(mpg)

16.8590

In [79]:
sum(float(d['hwy']) for d in mpg)/len(mpg)

23.4402

In [81]:
#for d in mpg:
    #print(d)

IndentationError: unexpected indent (<ipython-input-81-30de0cc3e4e5>, line 2)

In [85]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [87]:
citympgbycyl = []

for c in cylinders:
    summpg=0
    cyltypecount=0
    for d in mpg:
        if d['cyl']==c:
            summpg += float(d['cty']) 
            cyltypecount += 1
    citympgbycyl.append((c,summpg/cyltypecount))
citympgbycyl.sort(key = lambda x :x[0])
    
citympgbycyl

[('4', 21.0123), ('5', 20.5000), ('6', 16.2152), ('8', 12.5714)]

In [89]:
vehicleclass = set(d['class'] for d in mpg)
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [90]:
HwyMpgByClass = []

for t in vehicleclass:
    summpg = 0
    vclasscount =0
    for d in mpg:
        if d['class']==t:
            summpg += float(d['hwy'])
            vclasscount += 1
            
    HwyMpgByClass.append((t, summpg / vclasscount))
    
HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

[('pickup', 16.8788),
 ('suv', 18.1290),
 ('minivan', 22.3636),
 ('2seater', 24.8000),
 ('midsize', 27.2927),
 ('subcompact', 28.1429),
 ('compact', 28.2979)]

In [91]:
import datetime as dt
import time as tm

In [92]:
tm.time()

1569160262.6503

In [93]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2019, 9, 22, 19, 22, 15, 963112)

In [94]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second 

(2019, 9, 22, 19, 22, 15)

In [100]:
delta = dt.timedelta(days = 5) # create a timedelta of 100 days
delta

datetime.timedelta(days=5)

In [101]:
today = dt.date.today()

In [102]:
today

datetime.date(2019, 9, 22)

In [103]:
today - delta 

datetime.date(2019, 9, 17)

In [99]:
today > today-delta

True

In [2]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return str(person).split(',').split(' ')

split_title_and_name(people)
                     



AttributeError: 'list' object has no attribute 'split'

In [109]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'.format(title, lastname)

list(map(split_title_and_name, people))


['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [111]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}' .format (title,lastname)

list(map(split_title_and_name,people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [112]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True
True
True
True


True

In [5]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range(10)]


True

In [114]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

correct_answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

correct_answer[:50] # Display first 50 ids


['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa09',
 'aa10',
 'aa11',
 'aa12',
 'aa13',
 'aa14',
 'aa15',
 'aa16',
 'aa17',
 'aa18',
 'aa19',
 'aa20',
 'aa21',
 'aa22',
 'aa23',
 'aa24',
 'aa25',
 'aa26',
 'aa27',
 'aa28',
 'aa29',
 'aa30',
 'aa31',
 'aa32',
 'aa33',
 'aa34',
 'aa35',
 'aa36',
 'aa37',
 'aa38',
 'aa39',
 'aa40',
 'aa41',
 'aa42',
 'aa43',
 'aa44',
 'aa45',
 'aa46',
 'aa47',
 'aa48',
 'aa49']

In [115]:
class Person:
    department = 'School of Information'
    
    def set_name(self,new_name):
        self.name = new_name
    def set_location(self,new_location):
        self.location = new_location

In [116]:
person = Person()

In [117]:
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Christopher Brooks live in Ann Arbor, MI, USA and works in the department School of Information


In [118]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

In [119]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


In [120]:
my_function = lambda a, b, c : a + b

In [123]:
my_function(1,2,6)

3

In [125]:
#my_list = [number for number in range(0,999) if number%2==0]
#my_list

In [126]:
import numpy as np

In [127]:
mylist = [1,2,3,4]
x= np.array(mylist)
x

array([1, 2, 3, 4])

In [130]:
y =np.array([1,2,3,4])
y

array([1, 2, 3, 4])

In [132]:
y= np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
y.shape

(2, 3)

In [138]:
a= np.arange(0,30,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [139]:
n = a.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [141]:
o= np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [151]:
o.resize((3,3))


AttributeError: 'NoneType' object has no attribute 'resize'

In [150]:
 np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [152]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [153]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [156]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [157]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [158]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [163]:
p=np.ones([3,2],int)
p








array([[1, 1],
       [1, 1],
       [1, 1]])

In [164]:
np.vstack([p,2*p])

array([[1, 1],
       [1, 1],
       [1, 1],
       [2, 2],
       [2, 2],
       [2, 2]])

In [165]:
np.hstack([p,2*p])

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [1, 1, 2, 2]])

In [169]:
y=np.array([5,6,7,8])
y
x

array([1, 2, 3, 4])

In [170]:
y

array([5, 6, 7, 8])

In [171]:
x+y

array([ 6,  8, 10, 12])

In [172]:
x*y

array([ 5, 12, 21, 32])

In [173]:
x.dot(y)

70

In [174]:
z= np.array([y,y**2])
z

array([[ 5,  6,  7,  8],
       [25, 36, 49, 64]])

In [175]:
z.shape

(2, 4)

In [176]:
z.T

array([[ 5, 25],
       [ 6, 36],
       [ 7, 49],
       [ 8, 64]])

In [177]:
z.T.shape

(4, 2)

In [179]:
z.dtype

dtype('int64')

In [180]:
z=z.astype('f')
z.dtype

dtype('float32')

In [181]:
a=np.array([-4,-2,1,3,5])

In [182]:
a.sum()

3

In [183]:
a.max()

5

In [184]:
a.min()

-4

In [185]:


a.mean()

0.6

In [186]:
a.std()

3.2619012860600183

In [187]:
a.argmax() #index of max

4

In [189]:
a.argmin() #index of min

0

In [190]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [192]:
s[0],s[4],s[1:4]

(0, 16, array([1, 4, 9]))

In [193]:
s[1:5]

array([ 1,  4,  9, 16])

In [194]:
s[-5:]

array([ 64,  81, 100, 121, 144])

In [197]:
s[-5::2]

array([ 64, 100, 144])

In [198]:
r=np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [199]:
r[2,2]

14

In [200]:
r[3,3:6]

array([21, 22, 23])

In [201]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [202]:
r[-1,::2]

array([30, 32, 34])

In [203]:
r[r>30]

array([31, 32, 33, 34, 35])

In [204]:
r[r>30]=30

In [205]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [206]:
r2= r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [207]:
r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [208]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [210]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [211]:
r_copy[:]=10
r_copy

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [212]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [213]:
test = np.random.randint(0,10,(4,3))
test

array([[9, 2, 9],
       [9, 9, 9],
       [8, 2, 1],
       [4, 2, 0]])

In [214]:
len(test)

4

In [215]:
for row in test:
    print(row)

[9 2 9]
[9 9 9]
[8 2 1]
[4 2 0]


In [216]:
for i in range(len(test)):
    print(test[i])

[9 2 9]
[9 9 9]
[8 2 1]
[4 2 0]


In [220]:
for i ,row in enumerate(test):
    print('row' ,i, 'is' ,row)

row 0 is [9 2 9]
row 1 is [9 9 9]
row 2 is [8 2 1]
row 3 is [4 2 0]


In [221]:
test2 = test**2
test2

array([[81,  4, 81],
       [81, 81, 81],
       [64,  4,  1],
       [16,  4,  0]])

In [223]:
for i ,j in zip(test,test2): #to iterate throuugh both arrsays
    print(i,'+',j,'=' ,i+j)

[9 2 9] + [81  4 81] = [90  6 90]
[9 9 9] + [81 81 81] = [90 90 90]
[8 2 1] + [64  4  1] = [72  6  2]
[4 2 0] + [16  4  0] = [20  6  0]


In [224]:
 ['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [225]:
type([1,2,3])

list

In [226]:
type(lambda x: x+1) 

function

In [227]:
r = np.arange(36)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [228]:
r= r.reshape(6,6)

In [229]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [230]:
r[::7]

array([[0, 1, 2, 3, 4, 5]])

In [231]:
r[0:6,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [232]:
r[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [233]:
r.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])