In [1]:
firstname = 'Christopher arthur hansen brooks'.split(' ')[0]
lastname = 'Christopher arthur hansen brooks'.split(' ')[-1]
print(firstname)
print(lastname)

Christopher
brooks


In [2]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}

In [3]:
x['Christopher Brooks']

'brooksch@umich.edu'

In [4]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson'] 

In [5]:
for name in x:
    print(x[name])

brooksch@umich.edu
billg@microsoft.com
None


In [6]:
for emain in x.values():
    print(emain)

brooksch@umich.edu
billg@microsoft.com
None


In [7]:
for name , email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


In [8]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname,lname,email = x

In [9]:
fname,lname,email

('Christopher', 'Brooks', 'brooksch@umich.edu')

In [10]:
import csv
%precision 4
with open ('/root/Downloads/mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    

In [11]:
mpg

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [12]:
mpg[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [13]:
len(mpg)

234

In [14]:
type(mpg)

list

In [15]:
type(mpg[0])

collections.OrderedDict

In [16]:
mpg[0].keys

<function OrderedDict.keys>

In [17]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [20]:
for d in mpg :
    print(d.head())

AttributeError: 'collections.OrderedDict' object has no attribute 'head'

In [21]:
sum(float(d['cty']) for d in mpg)/len(mpg)

16.8590

In [22]:
sum(float(d['hwy']) for d in mpg)/len(mpg)

23.4402

In [23]:
 cylinder = set(d['cyl'] for d in mpg)

In [24]:
cylinder

{'4', '5', '6', '8'}

In [27]:
ctympgbycyl = []

for c in cylinder:
    sumpg = 0
    cyltypecount = 0
    for d in mpg:
        if d['cyl'] == c:
            sumpg+= float(d['cty'])
            cyltypecount+= 1
    ctympgbycyl.append((c,sumpg/cyltypecount))
ctympgbycyl.sort(key = lambda x:x[0])
    
ctympgbycyl

[('4', 21.0123), ('5', 20.5000), ('6', 16.2152), ('8', 12.5714)]

In [28]:
vehicleclass = set(d['class'] for d in mpg)

In [29]:
vehicleclass


{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [32]:
hwybyclass =[]

for t in vehicleclass:
    summpg = 0
    vclasscount = 0
    for d in mpg:
        if d['class']== t:
            summpg+= float(d['hwy'])
            vclasscount+=1
    hwybyclass.append((t,summpg/vclasscount))
hwybyclass.sort(key = lambda x:x[0])

hwybyclass

[('2seater', 24.8000),
 ('compact', 28.2979),
 ('midsize', 27.2927),
 ('minivan', 22.3636),
 ('pickup', 16.8788),
 ('subcompact', 28.1429),
 ('suv', 18.1290)]

In [33]:
import datetime as dt
import time as tm

In [34]:
tm.time()

1573717024.4594

In [35]:
dtnow = dt.datetime.fromtimestamp(tm.time())

In [36]:
dtnow

datetime.datetime(2019, 11, 14, 13, 8, 48, 898739)

In [41]:
dtnow.year, dtnow.second

(2019, 48)

In [42]:
delta = dt.timedelta(days = 167)
delta

datetime.timedelta(days=167)

In [49]:
today = dt.date(2019,7,17)

In [50]:
date = today+delta

In [51]:
date

datetime.date(2019, 12, 31)

In [52]:
today = dt .date.today()

In [53]:
today-delta

datetime.date(2019, 5, 31)

In [54]:
today>today-delta

True

In [59]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_lname(person):
    title = person.split(' ')[0]
    lname= person.split(' ')[-1]
    return '{} {}'.format(title,lname)

In [60]:
list(map(split_title_and_lname,people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [61]:
def time_tables():
    lst = []
    for i in range(10):
        for j in range(10):
            lst.append(i*j)
    return lst

In [62]:
time_tables()

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 0,
 4,
 8,
 12,
 16,
 20,
 24,
 28,
 32,
 36,
 0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 0,
 6,
 12,
 18,
 24,
 30,
 36,
 42,
 48,
 54,
 0,
 7,
 14,
 21,
 28,
 35,
 42,
 49,
 56,
 63,
 0,
 8,
 16,
 24,
 32,
 40,
 48,
 56,
 64,
 72,
 0,
 9,
 18,
 27,
 36,
 45,
 54,
 63,
 72,
 81]

In [64]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

correct_answer  = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

In [66]:
#correct_answer[:50]

In [67]:
class person:
    department = "information technology"
    def set_name(self,new_name):
        self.name = new_name
    def set_location(self,new_location):
        self.location = new_location

In [68]:
person = person()

In [70]:
person.set_name("chris")
person.set_location('Ann harbor in usa')
print('{} live in {} and works in department {}'.format(person.name,person.location,person.department))

chris live in Ann harbor in usa and works in department information technology


In [71]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = list(map(min,store1,store2))

In [72]:
cheapest

[9.0000, 11.0000, 12.3400, 2.0100]

In [73]:
import numpy as np

In [74]:
r = np.arange(36)

In [75]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [76]:
r = r.reshape(6,6)

In [77]:
r


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [80]:
r[1,:7]

array([ 6,  7,  8,  9, 10, 11])

In [84]:
r[:,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [83]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [87]:
r[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [89]:
r.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [91]:
r.reshape(36)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [92]:
test = np.random.randint(0,10,(4,3))

In [93]:
test

array([[4, 5, 8],
       [9, 2, 6],
       [5, 9, 7],
       [4, 1, 3]])

In [94]:
len(test)

4

In [97]:
for i in range(len(test)):
    print(test[i])

[4 5 8]
[9 2 6]
[5 9 7]
[4 1 3]


In [98]:
for i in test:
    print(i)

[4 5 8]
[9 2 6]
[5 9 7]
[4 1 3]


In [101]:
for i ,row in enumerate(test):
    print('row' ,i ,'is' ,row)

row 0 is [4 5 8]
row 1 is [9 2 6]
row 2 is [5 9 7]
row 3 is [4 1 3]


In [102]:
test2 = test**2

In [103]:
test2

array([[16, 25, 64],
       [81,  4, 36],
       [25, 81, 49],
       [16,  1,  9]])

In [105]:
for i , j in zip(test,test2):
    print(i,'+',j ,'=' ,i+j)

[4 5 8] + [16 25 64] = [20 30 72]
[9 2 6] + [81  4 36] = [90  6 42]
[5 9 7] + [25 81 49] = [30 90 56]
[4 1 3] + [16  1  9] = [20  2 12]


In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame([{'Name':'Chris','Item purchased':'Sponge','Cost':22.50},
                  {'Name':'Kevyn','Item purchased':'Kitty Litter','Cost':2.50},
                  {'Name':'Filip','Item purchased':'Spoon','Cost':5.00}],index=['Store1','Store1','Store2'])
df

Name Item purchased  Cost
Store1  Chris         Sponge  22.5
Store1  Kevyn   Kitty Litter   2.5
Store2  Filip          Spoon   5.0

In [4]:
df=  df.reset_index()

In [5]:
df

index   Name Item purchased  Cost
0  Store1  Chris         Sponge  22.5
1  Store1  Kevyn   Kitty Litter   2.5
2  Store2  Filip          Spoon   5.0

In [8]:
df['index']

0    Store1
1    Store1
2    Store2
Name: index, dtype: object

In [1]:
import pandas as pd

In [2]:
numbers = [1,2,None]

In [3]:
pd.Series(numbers,index=['a','b','c'])

a    1.0
b    2.0
c    NaN
dtype: float64